### ISSUE TITLE
wget: bad address 'block.energized.pro', and other weird errors

### ISSUE THREAD

**Issue by LoganDark** [EnergizedProtection/magisk#3]
![image](https://user-images.githubusercontent.com/4723091/100645865-25a55a00-32f2-11eb-9558-8aa774f057a4.png)

For some reason Energized is doing weeeeeeeeeeird things on my device. Update check spews errors in terminal, trying to add any pack does that ^...

![image](https://user-images.githubusercontent.com/4723091/100645992-4f5e8100-32f2-11eb-8f0b-d236c86ddce0.png)

Really not sure what secure means, but here is an older screenshot where Energized was working.

![image](https://user-images.githubusercontent.com/4723091/100646109-75842100-32f2-11eb-84d2-3dee2352b711.png)

What's going on?

**Comment by AvinashReddy3108** [comment]
I see that you're using a VPN [here](https://user-images.githubusercontent.com/4723091/100645992-4f5e8100-32f2-11eb-8f0b-d236c86ddce0.png), maybe try switching it off while doing the packs install/update and let us know if it helps?

**Comment by LoganDark** [comment]
Oof. NetGuard was the problem. That's really sad.

Thank you!

**Comment by LoganDark** [comment]
Looks like all VPN apps on Android 10 cause wget to change behavior and freak out like this. PIA causes the same thing.

**Comment by raulvasquez** [comment]
It's not just with a vpn. I have this issue on my op7pro without. There's issues with wget and ssl. I wish this module would rebase using curl instead

**Comment by LoganDark** [comment]
> It's not just with a vpn. I have this issue on my op7pro without. There's issues with wget and ssl. I wish this module would rebase using curl instead

That's not what rebase means. :)
